name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read

env:
  INSTANCE: 'Writerside/hi'
  ARTIFACT: 'webHelpHI2-all.zip'
  DOCKER_VERSION: '241.18775'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build index
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/i'
          artifact: 'webHelpI2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Build admin docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ag'
          artifact: 'webHelpAG2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Build admin docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ug'
          artifact: 'webHelpUG2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/webHelpI2-all.zip
            artifacts/webHelpAG2-all.zip
            artifacts/webHelpUG2-all.zip
          retention-days: 7
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip index
        run: unzip -O UTF-8 -qq webHelpI2-all.zip -d dir

      - name: Unzip admin guide
        run:  unzip -O UTF-8 -qq webHelpAG2-all.zip -d dir/admin

      - name: Unzip user guide
        run: unzip -O UTF-8 -qq webHelpUG2-all.zip -d dir/user

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4