name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read
  checks: read

env:
  DOCKER_VERSION: '241.18775'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build index
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/i'
          artifact: 'webHelpI2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save index
        uses: actions/upload-artifact@v4
        with:
          name: index
          path: |
            artifacts/webHelpI2-all.zip
          retention-days: 7

      - name: Build admin docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ag'
          artifact: 'webHelpAG2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save admin guide
        uses: actions/upload-artifact@v4
        with:
          name: admin
          path: |
            artifacts/webHelpAG2-all.zip
          retention-days: 7

      - name: Build user docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ug'
          artifact: 'webHelpUG2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save user guide
        uses: actions/upload-artifact@v4
        with:
          name: user
          path: |
            artifacts/webHelpUG2-all.zip
          retention-days: 7

      - name: Build developer docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/dg'
          artifact: 'webHelpDG2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save developer guide
        uses: actions/upload-artifact@v4
        with:
          name: developer
          path: |
            artifacts/webHelpDG2-all.zip
          retention-days: 7

      - name: Build BTS docs
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/bts'
          artifact: 'webHelpBTS2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save BTS guide
        uses: actions/upload-artifact@v4
        with:
          name: bts
          path: |
            artifacts/webHelpBTS2-all.zip
          retention-days: 7

      - name: Save swagger-ui folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: swagger-ui
          path: swagger-ui/*
          retention-days: 7

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Unzip index
        run: unzip -O UTF-8 -qq index/webHelpI2-all.zip -d dir

      - name: Unzip admin guide
        run:  unzip -O UTF-8 -qq admin/webHelpAG2-all.zip -d dir/admin

      - name: Unzip user guide
        run: unzip -O UTF-8 -qq user/webHelpUG2-all.zip -d dir/user

      - name: Unzip developer guide
        run: unzip -O UTF-8 -qq developer/webHelpDG2-all.zip -d dir/developer

      - name: Unzip BTS guide
        run: unzip -O UTF-8 -qq bts/webHelpBTS2-all.zip -d dir/bts

      - name: Copy Swagger-UI
        run: mkdir -p dir/openapi && cp -r swagger-ui/* dir/openapi/

      - name: Wait for OpenAPI specs to be uploaded
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Build and Upload OpenAPI Spec to Nexus'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Download OpenAPI specs
        run: |
          curl -o dir/openapi/cv3-all-bundled.yaml https://artifactory.cafevariome.org/repository/schemas/openapi/cv3-all-bundled.yaml
          curl -o dir/openapi/cv3-admin-bundled.yaml https://artifactory.cafevariome.org/repository/schemas/openapi/cv3-admin-bundled.yaml
          curl -o dir/openapi/cv3-network-bundled.yaml https://artifactory.cafevariome.org/repository/schemas/openapi/cv3-network-bundled.yaml
          curl -o dir/openapi/cv3-query-bundled.yaml https://artifactory.cafevariome.org/repository/schemas/openapi/cv3-query-bundled.yaml

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
