name: Build and Upload OpenAPI Spec to Nexus

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Bundle OpenAPI All spec
        run: redocly bundle Writerside/codeSnippets/openapi/openapi-all.json --output openapi/openapi-all-bundled.yaml

      - name: Bundle OpenAPI Admin spec
        run: redocly bundle Writerside/codeSnippets/openapi/openapi-admin.json --output openapi/openapi-admin-bundled.yaml

      - name: Upload OpenAPI specs to Nexus
        run: |
          curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" --upload-file openapi/openapi-all-bundled.yaml \
          https://artifactory.cafevariome.org/repository/schemas/openapi/cv3-all-bundled.yaml
          curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" --upload-file openapi/openapi-admin-bundled.yaml \
          https://artifactory.cafevariome.org/repository/schemas/openapi/cv3-admin-bundled.yaml
